// This file is generated by npm run build:icons

export type IconName =
	| 'document-fill'
	| 'document-outline'
	| 'home-fill'
	| 'home-outline'
	| 'login-logo'
	| 'notification-fill'
	| 'notification-outline'
