#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# npx lint-staged

# npx pretty-quick --staged


# LIST=`git diff-index --name-only --cached HEAD`; if [ "$LIST" ]; then npx prettier --write $LIST; git add $LIST; fi