import { makeStyles, shorthands } from '@fluentui/react-components'

export const useStyles = makeStyles({
  root: {
    width: '100%',
  },

  link: {
    paddingBottom: '8px',
    ...shorthands.border('0', 'solid', 'var(--always-dark-overlay)'),
    height: '60px',
    color: 'var(--secondary-text)',
    width: '100%',
    touchAction: 'manipulation',
    minWidth: 0,
    flexBasis: 'auto',
    marginTop: 0,
    marginBottom: 0,
    userSelect: 'none',
    display: 'flex',
    minHeight: 0,
    flexShrink: 0,
    cursor: 'pointer',
    paddingTop: '8px',
    outlineStyle: 'none',
    alignItems: 'stretch',
    flexDirection: 'row',
    marginLeft: 0,
    zIndex: 0,
    WebkitTapHighlightColor: 'transparent',
    backgroundColor: 'var(--primary-deemphasized-button-background)',
    paddingLeft: '4px',
    textAlign: 'inherit',
    paddingRight: '4px',
    marginRight: 0,
    listStyleType: 'none',
    textDecorationLine: 'none',
  },

  nested: {
    ...shorthands.borderWidth('0px'),
    ...shorthands.borderStyle('solid'),
    justifyContent: 'center',
    paddingLeft: 0,
    width: '100%',
    paddingTop: 0,
    minWidth: 0,
    flexDirection: 'column',
    wordBreak: 'keep-all',
    marginTop: 0,
    boxSizing: 'border-box',
    display: 'flex',
    alignItems: 'center',
    paddingRight: 0,
    minHeight: 0,
    flexShrink: 0,
    position: 'relative',
    zIndex: 0,
    flexGrow: 1,
    paddingBottom: 0,
    marginRight: 0,
  },
})
